spring:
  redis:
    port: 6379
    host: localhost
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mariadb://localhost:3306/checker
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 1234

  h2:
    console:
      path: /h2-console
      enabled: true

